#! /bin/sh

if [ -e "$BSPWM_TREE" ]; then
  bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
  rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

bspc config border_width        3
bspc config window_gap          8

bspc config focused_border_color '#2ad0bc'
bspc config presel_border_color  '#9d2435'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follow_pointer true

bspc monitor DP-0 -d I II III IV V 
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

launch_polybars
